# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
notifications:
  email: false
branches:
  only: master
# uncomment the following lines to allow failures on nightly julia
# (tests will run but not make your overall status red)
matrix:
  allow_failures:
  - julia: nightly

## uncomment following lines to deploy documentation
jobs:
   include:
     - stage: Documentation
       julia: 1.0
       os: linux
       script:
         - export JL_PKG=RegularizedLeastSquares
         - julia -e 'using Pkg; Pkg.instantiate()' #; Pkg.develop(PackageSpec(path=pwd()))'
         - julia --color=yes docs/make.jl
       after_success: skip
after_success:
  - julia --project=test/coverage -e 'using Pkg; Pkg.instantiate()'
  - julia --project=test/coverage test/coverage/coverage.jl
