# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
notifications:
  email: false
branches:
  only: master
# uncomment the following lines to allow failures on nightly julia
# (tests will run but not make your overall status red)
matrix:
  allow_failures:
  - julia: nightly
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("LinearSolver")); using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("LinearSolver")); using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("LinearSolver")); ENV["DOCUMENTER_DEBUG"] = "true"; include(joinpath("docs", "make.jl"))'
